application: zongo
version: 2
runtime: python
api_version: 1




handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /admin.*
  script: main.py
  login: admin
- url: /.*
  script: main.py
