application: zongo
version: 1
runtime: python
api_version: 1




handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /admin.*
  script: main.py
  login: admin
- url: /.*
  script: main.py

